/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_org_JNIInterface */

#ifndef _Included_com_jni_org_JNIInterface
#define _Included_com_jni_org_JNIInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_org_JNIInterface
 * Method:    isIDNumberLegal
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_org_JNIInterface_isIDNumberLegal
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
